### PR TITLE
Ensure precompile check works even w/o extension.

### PR DESCRIPTION
**Pull request by mattbrictson**
Fixes a problem where this correctly raises an error:

```
<%= stylesheet_link_tag("admin.css") %>
```

But this does not:

```
<%= stylesheet_link_tag("admin") %>
```

This is because the Rails tag helpers perform some magic to append the appropriate extension when searching for a matching asset. We have to do a similar trick. Otherwise a extension-less source will be matched by the
Sprockets `LOOSE_APP_ASSETS` proc and no precompile error will be raised.

### CODE REVIEW

**Comment by kenn** [comment]
+1

``` ruby
javascript_include_tag :jquery
```

won't work either.

Due to this issue, right now `sprockets_better_errors` is incompatible with [jquery-rails-cdn](https://github.com/kenn/jquery-rails-cdn).

**Comment by schneems** [comment]
I'm in favor of making this work. It actually isn't a problem in my PR to Rails. Is there some already existing function we can use to add the asset extension?

**Comment by mattbrictson** [comment]
Rails 3.2 and 4.x seem to work quite differently in this regard. In 4.x, there are `path_to_javascript` and `path_to_stylesheet` helpers that intelligently add the extensions. In 3.2, subclasses of `AssetIncludeTag` use the private `path_to_asset` method to add the extensions.

**Comment by schneems** [comment]
This was merged into sprockets and is no longer needed. I'm archiving this repo

**Pull request closed without merging**
