### PR TITLE
Level upto sprockets rails and support for Rails 4.2

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by NavyAnt24** [comment]
Is there any reason this has not been merged yet?

**Comment by schneems** [comment]
Good question. These checks were integrated with Rails 4.2 so having this gem in a Rails 4.2 app is redundant. Maybe we should add a warning or helpful error message?

**Comment by prathamesh-sonpatki** [comment]
@schneems May be add a note in README? Or do you think an error message if Rails version is > 4.2?

**Comment by NavyAnt24** [comment]
@prathamesh-sonpatki We are on Rails 4.1.9 and I had trouble installing this gem.

**Comment by schneems** [comment]
These features were merged into version 2.1.0 of sprockets-rails to be exact: https://github.com/rails/sprockets-rails/blob/master/CHANGELOG.md#210 if we were going to raise, we would want to raise based on this version and dependency

**Comment by schneems** [comment]
This was merged into sprockets and is no longer needed. I'm archiving this repo

**Pull request closed without merging**
